### ISSUE TITLE
Error when running on python 2.7

### ISSUE THREAD

**Issue by zakcostello** [JBEI/edd-utils#1]
Currently if this is installed and run in a python 2.7 environment, there are errors thrown.  We should modify the code to either prevent installation on python 2.7 or allow for its use on both versions.

**Comment by chimaerase** [comment]
Looks like there also isn't a requirements.txt file or a Pipfile yet.  I'd suggest using pipenv, which is the recommended solution for capturing package dependencies.  Setting a required Python version in the associated Pipfile will at least generate a warning when installed in a Python environment other than the one marked as required.
