### ISSUE TITLE
getpass.getuser issue in Google Colab

### ISSUE THREAD

**Issue by mkulawik** [JBEI/edd-utils#5]
Using edd_utils in a Google Colab notebook is a problem because "getpass.getuser" returns "root" as the user. Can this be changed to something like the following?

 37    # If not, get username / password from input
 38     if user is None:
 39         user = input("Enter your EDD Username: ")

**Comment by mkulawik** [comment]
It would probably be good to make the input lowercase while you're at it:
user = input("enter username: ").lower()

**Comment by wmorrell** [comment]
Why not just use the `~/.eddrc` config file instead? It's described at the end of the README file. Bypasses prompting for username/password in the notebook entirely.
